/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import unit.ChonDuocPhamNhapXuat;
import unit.controller.DuocPhamContronler;

/**
 *
 * @author admin
 */
public class frmChonDuocPham extends javax.swing.JFrame {

    /**
     * Creates new form frmChonDuocPham
     */
    public frmChonDuocPham() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();
        tbdanhsachdp.setModel(model);

        try {
            DuocPhamContronler pt = new DuocPhamContronler();
            ResultSet reset = pt.GetData();
            int i = 0;
            int k = 1;
            while ((reset != null) && (reset.next())) {
                model.setRowCount(++k);
                tbdanhsachdp.setValueAt(reset.getString("maduocpham"), i, 0);
                tbdanhsachdp.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbdanhsachdp.setValueAt(reset.getString("loaiduocpham"), i, 2);
                tbdanhsachdp.setValueAt(reset.getString("dutrutoida"), i, 3);
                tbdanhsachdp.setValueAt(reset.getString("soluong"), i, 4);
                tbdanhsachdp.setValueAt(reset.getString("donvitinh"), i, 5);
                tbdanhsachdp.setValueAt(reset.getString("gianhap"), i, 6);
                tbdanhsachdp.setValueAt(reset.getString("giaban"), i, 7);
                tbdanhsachdp.setValueAt(reset.getString("ghichu"), i, 8);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class.getName()).log(Level.SEVERE, null, ex);
        }

        tbdanhsachdp.setRowSelectionAllowed(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        panelChonDP = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtkeyword = new javax.swing.JTextField();
        lblchndp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdanhsachdp = new javax.swing.JTable();
        btnreset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 242, 242));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 242, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Danh Sách Dược Phẩm");

        jPanel2.setBackground(new java.awt.Color(255, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn dược phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        panelCenter.setLayout(new java.awt.GridLayout(1, 0));

        panelChonDP.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        txtkeyword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtkeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeywordActionPerformed(evt);
            }
        });
        txtkeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkeywordKeyReleased(evt);
            }
        });
        jPanel3.add(txtkeyword, java.awt.BorderLayout.CENTER);

        lblchndp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblchndp.setText("Tìm dược phẩm muốn tìm: ");
        jPanel3.add(lblchndp, java.awt.BorderLayout.LINE_START);

        panelChonDP.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tbdanhsachdp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbdanhsachdp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã dược phẩm", "Tên dược phẩm", "Loại dược phẩm", "Số lượng dự trữ", "Số lượng hiện có", "Đơn vị tính", "Giá nhập", "Giá bán", "Ghi chú"
            }
        ));
        tbdanhsachdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdanhsachdpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdanhsachdp);

        panelChonDP.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelCenter.add(panelChonDP);

        jPanel2.add(panelCenter, java.awt.BorderLayout.CENTER);

        btnreset.setBackground(new java.awt.Color(204, 0, 51));
        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Refesh");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(204, 0, 51));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtkeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeywordKeyReleased

    }//GEN-LAST:event_txtkeywordKeyReleased

    private void txtkeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeywordActionPerformed
        // TODO add your handling code here:
        String timkiem = txtkeyword.getText();
        DuocPhamContronler dp = new DuocPhamContronler();

        try {
            ResultSet reset = null;
            reset = dp.Timkiem(timkiem);
            DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();
            model.setRowCount(0);
            int i = 0;
            int k = 1;
            while (reset.next()) {
                model.setRowCount(++k);
                tbdanhsachdp.setValueAt(reset.getString("maduocpham"), i, 0);
                tbdanhsachdp.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbdanhsachdp.setValueAt(reset.getString("loaiduocpham"), i, 2);
                tbdanhsachdp.setValueAt(reset.getString("dutrutoida"), i, 3);
                tbdanhsachdp.setValueAt(reset.getString("soluong"), i, 4);
                tbdanhsachdp.setValueAt(reset.getString("donvitinh"), i, 5);
                tbdanhsachdp.setValueAt(reset.getString("gianhap"), i, 6);
                tbdanhsachdp.setValueAt(reset.getString("giaban"), i, 7);
                tbdanhsachdp.setValueAt(reset.getString("ghichu"), i, 8);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtkeywordActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtkeyword.setText("");
        DuocPhamContronler dp = new DuocPhamContronler();
        DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();
        model.setRowCount(0);
        try {
            ResultSet reset = dp.GetData();
            int i = 0;
            int k = 1;
            while (reset.next()) {
                model.setRowCount(++k);
                tbdanhsachdp.setValueAt(reset.getString("maduocpham"), i, 0);
                tbdanhsachdp.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbdanhsachdp.setValueAt(reset.getString("loaiduocpham"), i, 2);
                tbdanhsachdp.setValueAt(reset.getString("dutrutoida"), i, 3);
                tbdanhsachdp.setValueAt(reset.getString("soluong"), i, 4);
                tbdanhsachdp.setValueAt(reset.getString("donvitinh"), i, 5);
                tbdanhsachdp.setValueAt(reset.getString("gianhap"), i, 6);
                tbdanhsachdp.setValueAt(reset.getString("giaban"), i, 7);
                tbdanhsachdp.setValueAt(reset.getString("ghichu"), i, 8);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        try {
            // TODO add your handling code here:
            new frmQLPhieuNhap().setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    frmQLPhieuNhap jtRowData;
    frmQLPhieuXuat jxRowData;

    private void tbdanhsachdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdanhsachdpMouseClicked
        // TODO add your handling code here:

        int index = tbdanhsachdp.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();

        String madp = model.getValueAt(index, 0).toString();
        String tendp = model.getValueAt(index, 1).toString();
        String loaidp = model.getValueAt(index, 2).toString();
        String sldutru = model.getValueAt(index, 3).toString();
        String slhienco = model.getValueAt(index, 4).toString();
        String dvitinh = model.getValueAt(index, 5).toString();
        String gianhap = model.getValueAt(index, 6).toString();
        String giaban = model.getValueAt(index, 7).toString();
        String ghichu = model.getValueAt(index, 8).toString();
        try {
            jtRowData = new frmQLPhieuNhap();

        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        if (ChonDuocPhamNhapXuat.getLeggee() == 1) {
            jtRowData.setVisible(true);
            this.dispose();
            jtRowData.pack();
            jtRowData.setLocationRelativeTo(null);
            jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            jtRowData.txtduocpham.setText(madp);
            jtRowData.txtdvitinh.setText(dvitinh);
            jtRowData.txtgianhap.setText(gianhap);
        }

        try {
            jxRowData = new frmQLPhieuXuat();

        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        if (ChonDuocPhamNhapXuat.getLeggee() == 2) {
            jxRowData.setVisible(true);
            this.dispose();
            jxRowData.pack();
            jxRowData.setLocationRelativeTo(null);
            jxRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            jxRowData.txtduocpham.setText(madp);
            jxRowData.txtdvitinh.setText(dvitinh);
            jxRowData.txtgiaban.setText(giaban);
            jxRowData.txtghichu.setText(ghichu);
        }
    }//GEN-LAST:event_tbdanhsachdpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChonDuocPham.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmChonDuocPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblchndp;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelChonDP;
    private javax.swing.JTable tbdanhsachdp;
    private javax.swing.JTextField txtkeyword;
    // End of variables declaration//GEN-END:variables
}
