/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import unit.PhanQuyenUser;
import unit.controller.DuocPhamContronler;

/**
 *
 * @author admin
 */
public class frmMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLy
     *
     * @throws java.io.IOException
     */
    public frmMainFrame() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        if (PhanQuyenUser.getLogger() == 1) {
            btnqlkhachhang.setEnabled(false);
            btnqlnhacc.setEnabled(false);
            btnqlnhanvien.setEnabled(false);
        }

        try {
            DuocPhamContronler pt = new DuocPhamContronler();
            ResultSet reset = pt.GetData();
            int i = 0;
            while (reset.next()) {
                tbhienthitt.setValueAt(reset.getString("maduocpham"), i, 0);
                tbhienthitt.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbhienthitt.setValueAt(reset.getString("loaiduocpham"), i, 2);
                tbhienthitt.setValueAt(reset.getString("dutrutoida"), i, 3);
                tbhienthitt.setValueAt(reset.getString("soluong"), i, 4);
                tbhienthitt.setValueAt(reset.getString("donvitinh"), i, 5);
                tbhienthitt.setValueAt(reset.getString("gianhap"), i, 6);
                tbhienthitt.setValueAt(reset.getString("giaban"), i, 7);
                tbhienthitt.setValueAt(reset.getString("ghichu"), i, 8);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btndanhmucsp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnnhaphang = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnxuathang = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnxuattoathuoc = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnqlnhanvien = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jButton10 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnqlnhacc = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jButton13 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        btnqlkhachhang = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jButton15 = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jButton12 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbhienthitt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 255));

        jPanel1.setBackground(new java.awt.Color(244, 244, 255));

        jToolBar2.setBackground(new java.awt.Color(240, 232, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToolBar2.setRollover(true);
        jToolBar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToolBar2.setPreferredSize(new java.awt.Dimension(651, 45));
        jToolBar2.add(jSeparator9);
        jToolBar2.add(jSeparator10);

        btndanhmucsp.setBackground(new java.awt.Color(255, 153, 153));
        btndanhmucsp.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btndanhmucsp.setForeground(new java.awt.Color(153, 0, 51));
        btndanhmucsp.setText("Quản lý dược phẩm");
        btndanhmucsp.setFocusable(false);
        btndanhmucsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndanhmucsp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndanhmucsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhmucspActionPerformed(evt);
            }
        });
        jToolBar2.add(btndanhmucsp);
        jToolBar2.add(jSeparator1);

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);
        jToolBar2.add(jSeparator2);

        btnnhaphang.setBackground(new java.awt.Color(255, 153, 153));
        btnnhaphang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnnhaphang.setForeground(new java.awt.Color(153, 0, 51));
        btnnhaphang.setText("Nhập hàng");
        btnnhaphang.setFocusable(false);
        btnnhaphang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnhaphang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaphangActionPerformed(evt);
            }
        });
        jToolBar2.add(btnnhaphang);
        jToolBar2.add(jSeparator6);

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);
        jToolBar2.add(jSeparator5);

        btnxuathang.setBackground(new java.awt.Color(255, 153, 153));
        btnxuathang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnxuathang.setForeground(new java.awt.Color(153, 0, 51));
        btnxuathang.setText("Xuất hàng ");
        btnxuathang.setFocusable(false);
        btnxuathang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuathang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuathang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuathangActionPerformed(evt);
            }
        });
        jToolBar2.add(btnxuathang);
        jToolBar2.add(jSeparator3);

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);
        jToolBar2.add(jSeparator8);

        btnxuattoathuoc.setBackground(new java.awt.Color(255, 153, 153));
        btnxuattoathuoc.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnxuattoathuoc.setForeground(new java.awt.Color(153, 0, 51));
        btnxuattoathuoc.setText("Kê đơn thuốc");
        btnxuattoathuoc.setFocusable(false);
        btnxuattoathuoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuattoathuoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuattoathuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuattoathuocActionPerformed(evt);
            }
        });
        jToolBar2.add(btnxuattoathuoc);
        jToolBar2.add(jSeparator4);

        jButton5.setBackground(new java.awt.Color(0, 0, 153));
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);
        jToolBar2.add(jSeparator7);

        btnqlnhanvien.setBackground(new java.awt.Color(255, 153, 153));
        btnqlnhanvien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnqlnhanvien.setForeground(new java.awt.Color(153, 0, 51));
        btnqlnhanvien.setText("Quản lý nhân viên");
        btnqlnhanvien.setFocusable(false);
        btnqlnhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnqlnhanvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnhanvienActionPerformed(evt);
            }
        });
        jToolBar2.add(btnqlnhanvien);
        jToolBar2.add(jSeparator11);

        jButton10.setBackground(new java.awt.Color(0, 0, 153));
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton10);
        jToolBar2.add(jSeparator12);

        btnqlnhacc.setBackground(new java.awt.Color(255, 153, 153));
        btnqlnhacc.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnqlnhacc.setForeground(new java.awt.Color(153, 0, 51));
        btnqlnhacc.setText("Quản lý nhà cung cấp");
        btnqlnhacc.setFocusable(false);
        btnqlnhacc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnqlnhacc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnqlnhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnhaccActionPerformed(evt);
            }
        });
        jToolBar2.add(btnqlnhacc);
        jToolBar2.add(jSeparator13);

        jButton13.setBackground(new java.awt.Color(0, 0, 153));
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton13);
        jToolBar2.add(jSeparator14);

        btnqlkhachhang.setBackground(new java.awt.Color(255, 153, 153));
        btnqlkhachhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnqlkhachhang.setForeground(new java.awt.Color(153, 0, 51));
        btnqlkhachhang.setText("Quản lý khách hàng");
        btnqlkhachhang.setFocusable(false);
        btnqlkhachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnqlkhachhang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnqlkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlkhachhangActionPerformed(evt);
            }
        });
        jToolBar2.add(btnqlkhachhang);
        jToolBar2.add(jSeparator17);

        jButton15.setBackground(new java.awt.Color(0, 0, 153));
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton15);
        jToolBar2.add(jSeparator18);

        jButton12.setBackground(new java.awt.Color(204, 0, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 255, 51));
        jButton12.setText("Đăng xuất ");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton12);
        jToolBar2.add(jSeparator15);
        jToolBar2.add(jSeparator16);

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hiển thị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbhienthitt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbhienthitt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã dược phẩm", "Tên dược phẩm", "Loại dược phẩm", "SL dự trữ tối thiểu", "SL hiện có", "Đơn vị tính", "Giá nhập", "Giá bán", "Ghi chú"
            }
        ));
        tbhienthitt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbhienthitt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhienthittMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbhienthitt);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hệ Thống Quản Lý Dược Phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Nhà Thuốc Cung Cấp Dược Phẩm Đông Nam Á");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndanhmucspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhmucspActionPerformed
        // TODO add your handling code here:
        new frmQLDuocPhamThuoc().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btndanhmucspActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        new frmDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnnhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaphangActionPerformed
        try {
            // TODO add your handling code here:
            new frmQLPhieuNhap().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnnhaphangActionPerformed

    private void btnxuathangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuathangActionPerformed
        try {
            // TODO add your handling code here:
            new frmQLPhieuXuat().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnxuathangActionPerformed

    private void btnxuattoathuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuattoathuocActionPerformed
        // TODO add your handling code here:
        new frmQLToaThuoc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnxuattoathuocActionPerformed

    private void btnqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnhanvienActionPerformed
        try {
            // TODO add your handling code here:
            new frmQLNhanVien().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(frmMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnqlnhanvienActionPerformed

    private void btnqlnhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnhaccActionPerformed
        // TODO add your handling code here:
        new frmQLNhaCC().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnqlnhaccActionPerformed

    private void btnqlkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlkhachhangActionPerformed
        // TODO add your handling code here:
        new frmQLKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnqlkhachhangActionPerformed

    private void tbhienthittMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhienthittMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbhienthittMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frmMainFrame frmMain = null;
                try {
                    frmMain = new frmMainFrame();
                } catch (IOException ex) {
                    Logger.getLogger(frmMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                frmMain.setLocationRelativeTo(null);
                try {
                    new frmMainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(frmMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhmucsp;
    private javax.swing.JButton btnnhaphang;
    private javax.swing.JButton btnqlkhachhang;
    private javax.swing.JButton btnqlnhacc;
    private javax.swing.JButton btnqlnhanvien;
    private javax.swing.JButton btnxuathang;
    private javax.swing.JButton btnxuattoathuoc;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tbhienthitt;
    // End of variables declaration//GEN-END:variables
}
