/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import unit.ChonDuocPhamNhapXuat;
import unit.controller.DuocPhamContronler;
import unit.controller.PhieuNhapContronler;
import unit.data.JDBCConnection;
import works.DateTimeMaster;

/**
 *
 * @author admin
 */
public class frmQLPhieuNhap extends javax.swing.JFrame {

    /**
     * Creates new form frmQLPhieuNhap
     */
    public frmQLPhieuNhap() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtsolo.requestFocus();
        txtngaynhap.setText(java.time.LocalDate.now().toString());
        cbbNgay1.setSelectedItem(DateTimeMaster.getDate());
        cbbNgay2.setSelectedItem(DateTimeMaster.getDate());
        cbbThang1.setSelectedItem(DateTimeMaster.getMonth());
        cbbThang2.setSelectedItem(DateTimeMaster.getMonth());
        //year
        int y = Integer.parseInt(DateTimeMaster.getYear());
        Vector v = new Vector();
        for (int i = y - 5; i <= y + 5; i++) {
            v.add(i + "");
        }
        cbbNam1.setModel(new DefaultComboBoxModel(v));
        cbbNam2.setModel(new DefaultComboBoxModel(v));
        //
        cbbNam1.setSelectedItem(DateTimeMaster.getYear());
        cbbNam2.setSelectedItem(DateTimeMaster.getYear());
        txtngaysx.setText("");
        txthsd.setText("");

        tbhienthi.removeAll();
        Statement st = null;
        ResultSet reset = null;
        java.sql.Connection conn = JDBCConnection.getJDBCConnection();
        st = conn.createStatement();

        reset = st.executeQuery("select *from nhacungcap");
        Vector<String> data1 = new Vector<String>();
        while (reset.next()) {
            data1.addElement(reset.getString("manhacc"));
            cbonhacc.setModel(new DefaultComboBoxModel(data1));
        }

        try {
            PhieuNhapContronler pt = new PhieuNhapContronler();
            reset = pt.GetData();
            int i = 0;
            while (reset.next()) {
                tbhienthi.setValueAt(reset.getString("sophieunhap"), i, 0);
                tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbhienthi.setValueAt(reset.getString("ngaynhap"), i, 2);
                tbhienthi.setValueAt(reset.getString("solo"), i, 3);
                tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                tbhienthi.setValueAt(reset.getString("ngaysanxuat"), i, 6);
                tbhienthi.setValueAt(reset.getString("hansudung"), i, 7);
                tbhienthi.setValueAt(reset.getString("tennhacc"), i, 8);
                tbhienthi.setValueAt(reset.getString("gianhap"), i, 9);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtmaphieu = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txtngaynhap = new javax.swing.JTextField();
        butNgay = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtsolo = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtdvitinh = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtngaysx = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        cbbNgay1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbbThang1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbbNam1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txthsd = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        cbbNgay2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cbbThang2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cbbNam2 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtduocpham = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtgianhap = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbonhacc = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhienthi = new javax.swing.JTable();
        btnchondp = new javax.swing.JButton();
        butSuaPhieuNhap = new javax.swing.JButton();
        butPhieuMoi = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        butNhapHang = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PHIẾU NHẬP HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(479, 479, 479))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhập hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel24.setLayout(new java.awt.GridLayout(10, 0));

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel9.setText(" Mã phiếu*");
        jLabel9.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel10.add(jLabel9, java.awt.BorderLayout.WEST);

        txtmaphieu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtmaphieu.setEnabled(false);
        jPanel10.add(txtmaphieu, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        txtngaynhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtngaynhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaynhapActionPerformed(evt);
            }
        });
        jPanel11.add(txtngaynhap, java.awt.BorderLayout.CENTER);

        butNgay.setBackground(new java.awt.Color(242, 242, 242));
        butNgay.setText(" Ngày*");
        butNgay.setFocusable(false);
        butNgay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        butNgay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butNgay.setMargin(new java.awt.Insets(2, 2, 2, 2));
        butNgay.setPreferredSize(new java.awt.Dimension(70, 20));
        butNgay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNgayActionPerformed(evt);
            }
        });
        jPanel11.add(butNgay, java.awt.BorderLayout.LINE_START);

        jPanel24.add(jPanel11);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(" Số lô*");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel6.add(jLabel3, java.awt.BorderLayout.WEST);

        txtsolo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsolo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsoloFocusGained(evt);
            }
        });
        txtsolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoloActionPerformed(evt);
            }
        });
        jPanel6.add(txtsolo, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel6);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel6.setText(" Số lượng*");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel5.add(jLabel6, java.awt.BorderLayout.WEST);

        txtsoluong.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsoluong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsoluongFocusGained(evt);
            }
        });
        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });
        jPanel5.add(txtsoluong, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel5);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setText(" Đơn vị tính*");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel7.add(jLabel7, java.awt.BorderLayout.WEST);

        txtdvitinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtdvitinh.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtdvitinh.setEnabled(false);
        jPanel7.add(txtdvitinh, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel7);

        jPanel24.add(jPanel20);

        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel2.setText(" Ngày SX*");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel25.add(jLabel2, java.awt.BorderLayout.WEST);

        jPanel13.setLayout(new java.awt.BorderLayout());

        txtngaysx.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtngaysx.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtngaysx.setEnabled(false);
        jPanel13.add(txtngaysx, java.awt.BorderLayout.CENTER);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        cbbNgay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgay1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNgay1);

        jLabel10.setText("/");
        jPanel16.add(jLabel10);

        cbbThang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbThang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThang1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbThang1);

        jLabel12.setText("/");
        jPanel16.add(jLabel12);

        cbbNam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013" }));
        cbbNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNam1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNam1);

        jLabel14.setText(" ");
        jPanel16.add(jLabel14);

        jPanel13.add(jPanel16, java.awt.BorderLayout.WEST);

        jPanel22.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel13.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jPanel25.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel25);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setText(" Hạn SD*");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel3.add(jLabel4, java.awt.BorderLayout.WEST);

        jPanel14.setLayout(new java.awt.BorderLayout());

        txthsd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txthsd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txthsd.setEnabled(false);
        jPanel14.add(txthsd, java.awt.BorderLayout.CENTER);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        cbbNgay2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbNgay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgay2ActionPerformed(evt);
            }
        });
        jPanel17.add(cbbNgay2);

        jLabel15.setText("/");
        jPanel17.add(jLabel15);

        cbbThang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbThang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThang2ActionPerformed(evt);
            }
        });
        jPanel17.add(cbbThang2);

        jLabel16.setText("/");
        jPanel17.add(jLabel16);

        cbbNam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013" }));
        cbbNam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNam2ActionPerformed(evt);
            }
        });
        jPanel17.add(cbbNam2);

        jLabel17.setText(" ");
        jPanel17.add(jLabel17);

        jPanel14.add(jPanel17, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel3);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel13.setText(" Giá nhập*");
        jLabel13.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel18.add(jLabel13, java.awt.BorderLayout.WEST);

        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGiaNhap.setPreferredSize(new java.awt.Dimension(64, 15));
        txtGiaNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiaNhapFocusGained(evt);
            }
        });
        jPanel18.add(txtGiaNhap, java.awt.BorderLayout.CENTER);

        jLabel8.setText("Tên dược phẩm");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 20));

        txtduocpham.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtduocpham.setEnabled(false);
        txtduocpham.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtduocphamFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtduocpham, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtduocpham, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel18.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel24.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel18.setText(" Giá nhập*");
        jLabel18.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel19.add(jLabel18, java.awt.BorderLayout.WEST);

        txtgianhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtgianhap.setEnabled(false);
        txtgianhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgianhapFocusGained(evt);
            }
        });
        jPanel19.add(txtgianhap, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel19);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Nhà cung cấp");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel4.add(jLabel5, java.awt.BorderLayout.LINE_START);

        cbonhacc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbonhacc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cbonhacc, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel4);

        jPanel2.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Nhập Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N

        tbhienthi.setBackground(new java.awt.Color(244, 244, 255));
        tbhienthi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbhienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Tên dược phẩm", "Ngày nhập", "Số lô", "Số lượng ", "Đơn vị tính", "Ngày sản xuất", "Hạn sử dụng", "Nhà cung cấp", "Giá nhập hàng"
            }
        ));
        tbhienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhienthi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        btnchondp.setBackground(new java.awt.Color(102, 0, 51));
        btnchondp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnchondp.setForeground(new java.awt.Color(255, 255, 255));
        btnchondp.setText("Chọn Dược Phẩm");
        btnchondp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchondpActionPerformed(evt);
            }
        });

        butSuaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butSuaPhieuNhap.setText("Sửa Phiếu Nhập");
        butSuaPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butSuaPhieuNhapMouseExited(evt);
            }
        });
        butSuaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSuaPhieuNhapActionPerformed(evt);
            }
        });

        butPhieuMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butPhieuMoi.setText("Phiếu Mới");
        butPhieuMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPhieuMoiActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(204, 0, 51));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        butNhapHang.setBackground(new java.awt.Color(153, 153, 153));
        butNhapHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butNhapHang.setText("Nhập Phiếu");
        butNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butNhapHangMouseExited(evt);
            }
        });
        butNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNhapHangActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Xóa Phiếu");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(579, 587, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnchondp)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butPhieuMoi)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(butSuaPhieuNhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnchondp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butSuaPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butPhieuMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNgayActionPerformed

    }//GEN-LAST:event_butNgayActionPerformed

    private boolean checkInputOK() {
        if (txtngaynhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ngày nhập chưa hiển thị");
            return false;
        }
        if (txtsolo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Số Lô");
            return false;
        }
        if (txtngaysx.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Ngày Sản Xuất");
            return false;
        }
        if (txthsd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Hạn Sử Dụng");
            return false;
        }
        if (txtsoluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Số Lượng");
            return false;
        }
        try {
            if (Integer.parseInt(txtsoluong.getText()) < 0) {
                throw new Exception();
            }
            if (Integer.parseInt(txtgianhap.getText()) < 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng, giá nhập, giá bán phải là số >= 0");
            return false;
        }
        return true;
    }

    private void txtsoloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsoloFocusGained


    }//GEN-LAST:event_txtsoloFocusGained

    private void txtsoluongFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsoluongFocusGained

    }//GEN-LAST:event_txtsoluongFocusGained

    private void cbbNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgay1ActionPerformed
        txtngaysx.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNgay1ActionPerformed

    private void cbbThang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThang1ActionPerformed
        txtngaysx.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbThang1ActionPerformed

    private void cbbNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNam1ActionPerformed
        txtngaysx.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNam1ActionPerformed

    private void cbbNgay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgay2ActionPerformed
        txthsd.setText(cbbNam2.getSelectedItem() + "-" + cbbThang2.getSelectedItem() + "-" + cbbNgay2.getSelectedItem());
    }//GEN-LAST:event_cbbNgay2ActionPerformed

    private void cbbThang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThang2ActionPerformed
        txthsd.setText(cbbNam2.getSelectedItem() + "-" + cbbThang2.getSelectedItem() + "-" + cbbNgay2.getSelectedItem());
    }//GEN-LAST:event_cbbThang2ActionPerformed

    private void cbbNam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNam2ActionPerformed
        txthsd.setText(cbbNam2.getSelectedItem() + "-" + cbbThang2.getSelectedItem() + "-" + cbbNgay2.getSelectedItem());
    }//GEN-LAST:event_cbbNam2ActionPerformed

    private void txtGiaNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaNhapFocusGained
        txtGiaNhap.selectAll();
    }//GEN-LAST:event_txtGiaNhapFocusGained

    private void txtgianhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgianhapFocusGained
        txtgianhap.selectAll();
    }//GEN-LAST:event_txtgianhapFocusGained

    private void butPhieuMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPhieuMoiActionPerformed
        txtmaphieu.setText("");
        txtsolo.setText("");
        txtdvitinh.setText("");
        txtngaysx.setText("");
        txthsd.setText("");
        txtsoluong.setText("");
        txtgianhap.setText("");
        txtngaynhap.setText(java.time.LocalDate.now().toString());
    }//GEN-LAST:event_butPhieuMoiActionPerformed

    private void butNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butNhapHangMouseExited

    }//GEN-LAST:event_butNhapHangMouseExited

    private void butNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNhapHangActionPerformed
        ResultSet reset = null;
        PhieuNhapContronler a = new PhieuNhapContronler();
        DuocPhamContronler dp = new DuocPhamContronler();

        if (checkInputOK()) {
            String tendp = txtduocpham.getText();
            String ngaynhap = txtngaynhap.getText();
            int solo = Integer.parseInt(txtsolo.getText());
            String dvitinh = txtdvitinh.getText();
            double gianhap = Double.parseDouble(txtgianhap.getText());
            String ngaysx = txtngaysx.getText();
            String hansd = txthsd.getText();
            int soluong = Integer.parseInt(txtsoluong.getText());
            String nhacc = cbonhacc.getSelectedItem().toString();

            try {
                reset = dp.GetSoLuong(tendp);

                ResultSet reset1 = null;
                while (reset.next()) {
                    reset1 = dp.GetDuTruToiThieu(tendp);
                    int kiemtraSL = reset.getInt("soluong") + soluong;
                    while (reset1.next()) {
                        if (reset1.getInt("dutrutoida") <= kiemtraSL) {
                            JOptionPane.showMessageDialog(null, "Số lượng thêm vào có tổng phải nhỏ hơn số lượng tối đa");
                        } else {
                            dp.SetSoLuong(tendp, soluong + reset.getInt("soluong"));

                            a.Insert(tendp, ngaynhap, solo, soluong, dvitinh, ngaysx, hansd, nhacc, gianhap);

                            DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
                            model.setRowCount(0);
                            reset = a.GetData();
                            int i = 0;
                            int k = 1;
                            while (reset.next()) {
                                model.setRowCount(++k);
                                tbhienthi.setValueAt(reset.getString("sophieunhap"), i, 0);
                                tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                                tbhienthi.setValueAt(reset.getString("ngaynhap"), i, 2);
                                tbhienthi.setValueAt(reset.getString("solo"), i, 3);
                                tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                                tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                                tbhienthi.setValueAt(reset.getString("ngaysanxuat"), i, 6);
                                tbhienthi.setValueAt(reset.getString("hansudung"), i, 7);
                                tbhienthi.setValueAt(reset.getString("tennhacc"), i, 8);
                                tbhienthi.setValueAt(reset.getString("gianhap"), i, 9);
                                i++;
                            }
                        }
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            } catch (IOException ex) {
                Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_butNhapHangActionPerformed

    private void butSuaPhieuNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSuaPhieuNhapMouseExited

    }//GEN-LAST:event_butSuaPhieuNhapMouseExited

    private void butSuaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSuaPhieuNhapActionPerformed
        PhieuNhapContronler a = new PhieuNhapContronler();
        DuocPhamContronler dp = new DuocPhamContronler();
        ResultSet reset = null;
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        String sopn = tbhienthi.getValueAt(chondong, 0) + "";
        String tendp = txtduocpham.getText();
        String ngaynhap = txtngaynhap.getText();
        int solo = Integer.parseInt(txtsolo.getText());
        String ngaysx = txtngaysx.getText();
        String hansd = txthsd.getText();
        int soluong = Integer.parseInt(txtsoluong.getText());
        String nhacc = cbonhacc.getSelectedItem().toString();

        try {
            a.Update(sopn, ngaynhap, solo, soluong, ngaysx, hansd, nhacc);

            DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
            model.setRowCount(0);
            reset = a.GetData();
            int i = 0;
            int k = 1;
            while (reset.next()) {
                model.setRowCount(++k);
                tbhienthi.setValueAt(reset.getString("sophieunhap"), i, 0);
                tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbhienthi.setValueAt(reset.getString("ngaynhap"), i, 2);
                tbhienthi.setValueAt(reset.getString("solo"), i, 3);
                tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                tbhienthi.setValueAt(reset.getString("ngaysanxuat"), i, 6);
                tbhienthi.setValueAt(reset.getString("hansudung"), i, 7);
                tbhienthi.setValueAt(reset.getString("tennhacc"), i, 8);
                tbhienthi.setValueAt(reset.getString("gianhap"), i, 9);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_butSuaPhieuNhapActionPerformed

    private void btnchondpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchondpActionPerformed
        // TODO add your handling code here:
        new frmChonDuocPham().setVisible(true);
        ChonDuocPhamNhapXuat.setLeggee(1);
        this.dispose();
    }//GEN-LAST:event_btnchondpActionPerformed

    private void txtduocphamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtduocphamFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtduocphamFocusGained

    private void tbhienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhienthiMouseClicked
        // TODO add your handling code here:
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        txtmaphieu.setText(tbhienthi.getValueAt(chondong, 0) + "");
        txtduocpham.setText(tbhienthi.getValueAt(chondong, 1) + "");
        txtngaynhap.setText(tbhienthi.getValueAt(chondong, 2) + "");
        txtsolo.setText(tbhienthi.getValueAt(chondong, 3) + "");
        txtsoluong.setText(tbhienthi.getValueAt(chondong, 4) + "");
        txtdvitinh.setText(tbhienthi.getValueAt(chondong, 5) + "");
        txtngaysx.setText(tbhienthi.getValueAt(chondong, 6) + "");
        txthsd.setText(tbhienthi.getValueAt(chondong, 7) + "");
        cbonhacc.setSelectedItem(tbhienthi.getValueAt(chondong, 8) + "");
        txtgianhap.setText(tbhienthi.getValueAt(chondong, 9) + "");
    }//GEN-LAST:event_tbhienthiMouseClicked

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        try {
            // TODO add your handling code here:
            new frmMainFrame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        PhieuNhapContronler pn = new PhieuNhapContronler();
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        String sopn = tbhienthi.getValueAt(chondong, 0) + " ";
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        } else {
            try {
                pn.Delete(sopn);
                DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
                model.setRowCount(0);
                ResultSet reset = pn.GetData();
                int i = 0;
                int k = 1;
                while (reset.next()) {
                    model.setRowCount(++k);
                    tbhienthi.setValueAt(reset.getString("sophieunhap"), i, 0);
                    tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                    tbhienthi.setValueAt(reset.getString("ngaynhap"), i, 2);
                    tbhienthi.setValueAt(reset.getString("solo"), i, 3);
                    tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                    tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                    tbhienthi.setValueAt(reset.getString("ngaysanxuat"), i, 6);
                    tbhienthi.setValueAt(reset.getString("hansudung"), i, 7);
                    tbhienthi.setValueAt(reset.getString("tennhacc"), i, 8);
                    tbhienthi.setValueAt(reset.getString("gianhap"), i, 9);
                    i++;
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtngaynhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaynhapActionPerformed
        // TODO add your handling code here:
        txtsolo.requestFocus();
    }//GEN-LAST:event_txtngaynhapActionPerformed

    private void txtsoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoloActionPerformed
        // TODO add your handling code here:
        txtsoluong.requestFocus();
    }//GEN-LAST:event_txtsoloActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
        cbonhacc.requestFocus();
    }//GEN-LAST:event_txtsoluongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frmQLPhieuNhap().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmQLPhieuNhap.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    public javax.swing.JButton btnchondp;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton butNgay;
    private javax.swing.JButton butNhapHang;
    private javax.swing.JButton butPhieuMoi;
    private javax.swing.JButton butSuaPhieuNhap;
    private javax.swing.JComboBox cbbNam1;
    private javax.swing.JComboBox cbbNam2;
    private javax.swing.JComboBox cbbNgay1;
    private javax.swing.JComboBox cbbNgay2;
    private javax.swing.JComboBox cbbThang1;
    private javax.swing.JComboBox cbbThang2;
    private javax.swing.JComboBox<String> cbonhacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhienthi;
    private javax.swing.JTextField txtGiaNhap;
    public javax.swing.JTextField txtduocpham;
    public javax.swing.JTextField txtdvitinh;
    public javax.swing.JTextField txtgianhap;
    public javax.swing.JTextField txthsd;
    private javax.swing.JTextField txtmaphieu;
    public javax.swing.JTextField txtngaynhap;
    public javax.swing.JTextField txtngaysx;
    private javax.swing.JTextField txtsolo;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
