/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import unit.ChonDuocPhamNhapXuat;
import unit.controller.DuocPhamContronler;
import unit.controller.PhieuXuatContronler;
import unit.data.JDBCConnection;
import works.DateTimeMaster;

/**
 *
 * @author admin
 */
public class frmQLPhieuXuat extends javax.swing.JFrame {

    /**
     * Creates new form frmQLPhieuXuat
     * @throws java.sql.SQLException
     */
    public frmQLPhieuXuat() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        txtngayxuat.setText(java.time.LocalDate.now().toString());
        cbbNgay1.setSelectedItem(DateTimeMaster.getDate());
        cbbThang1.setSelectedItem(DateTimeMaster.getMonth());
        //year
        int y = Integer.parseInt(DateTimeMaster.getYear());
        Vector v = new Vector();
        for (int i = y - 5; i <= y + 5; i++) {
            v.add(i + "");
        }
        cbbNam1.setModel(new DefaultComboBoxModel(v));
        //
        cbbNam1.setSelectedItem(DateTimeMaster.getYear());

        tbhienthi.removeAll();
        Statement st = null;
        ResultSet reset = null;
        java.sql.Connection conn = JDBCConnection.getJDBCConnection();
        st = conn.createStatement();

        reset = st.executeQuery("select *from khachhang");
        Vector<String> data1 = new Vector<String>();
        while (reset.next()) {
            data1.addElement(reset.getString("makhach"));
            cbokhachhang.setModel(new DefaultComboBoxModel(data1));
        }

        try {
            PhieuXuatContronler pt = new PhieuXuatContronler();
            reset = pt.GetData();
            int i = 0;
            while (reset.next()) {
                tbhienthi.setValueAt(reset.getString("maphieuxuat"), i, 0);
                tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbhienthi.setValueAt(reset.getString("ngayxuat"), i, 2);
                tbhienthi.setValueAt(reset.getString("tenkhach"), i, 3);
                tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                tbhienthi.setValueAt(reset.getString("giaban"), i, 6);
                tbhienthi.setValueAt(reset.getString("ghichu"), i, 7);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhienthi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmaphieu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtduocpham = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtngayxuat = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        cbbNgay1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbbThang1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbbNam1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbokhachhang = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtdvitinh = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtgiaban = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtghichu = new javax.swing.JTextField();
        btnchondp = new javax.swing.JButton();
        butNhapHang = new javax.swing.JButton();
        butSuaPhieuNhap = new javax.swing.JButton();
        butPhieuMoi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PHIẾU XUẤT HÀNG");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Xuất Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 51))); // NOI18N

        tbhienthi.setBackground(new java.awt.Color(244, 244, 255));
        tbhienthi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbhienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số phiếu nhập", "Tên dược phẩm", "Ngày xuất", "Khách hàng", "Số lượng ", "Đơn vị tính", "Giá bán", "Ghi chú"
            }
        ));
        tbhienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhienthi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin xuất hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("Mã phiếu xuất");

        txtmaphieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmaphieu.setEnabled(false);
        txtmaphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaphieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtmaphieu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setText("Tên dược phẩm");

        txtduocpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtduocpham.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtduocpham, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtduocpham, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel4.setText("Ngày xuất ");

        txtngayxuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtngayxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayxuatActionPerformed(evt);
            }
        });

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        cbbNgay1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbNgay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgay1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNgay1);

        jLabel10.setText("/");
        jPanel16.add(jLabel10);

        cbbThang1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbThang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbThang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThang1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbThang1);

        jLabel12.setText("/");
        jPanel16.add(jLabel12);

        cbbNam1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbbNam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013" }));
        cbbNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNam1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNam1);

        jLabel14.setText(" ");
        jPanel16.add(jLabel14);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtngayxuat)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel5.setText("Số lượng");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel6.setText("Khách hàng");

        cbokhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbokhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbokhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokhachhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cbokhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbokhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setText("Đơn vị tính");

        txtdvitinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtdvitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdvitinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtdvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtdvitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel8.setText("Giá bán");

        txtgiaban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtgiaban.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtgiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtgiaban, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel9.setText("Ghi chú");

        txtghichu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtghichu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnchondp.setBackground(new java.awt.Color(102, 0, 51));
        btnchondp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnchondp.setForeground(new java.awt.Color(255, 255, 255));
        btnchondp.setText("Chọn Dược Phẩm");
        btnchondp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchondpActionPerformed(evt);
            }
        });

        butNhapHang.setBackground(new java.awt.Color(153, 153, 153));
        butNhapHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        butNhapHang.setText("Xuất Phiếu");
        butNhapHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        butNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butNhapHangMouseExited(evt);
            }
        });
        butNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNhapHangActionPerformed(evt);
            }
        });

        butSuaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butSuaPhieuNhap.setText("Update phiếu xuất");
        butSuaPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butSuaPhieuNhapMouseExited(evt);
            }
        });
        butSuaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSuaPhieuNhapActionPerformed(evt);
            }
        });

        butPhieuMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butPhieuMoi.setText("Phiếu xuất mới");
        butPhieuMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPhieuMoiActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete phiếu xuất");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(204, 0, 51));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(butPhieuMoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnchondp)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnDelete)
                                .addGap(32, 32, 32)
                                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(butNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(butSuaPhieuNhap)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnchondp)
                            .addComponent(butNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butSuaPhieuNhap))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butPhieuMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclose))
                        .addGap(23, 23, 23))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbhienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhienthiMouseClicked
        // TODO add your handling code here:
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        txtmaphieu.setText(tbhienthi.getValueAt(chondong, 0) + "");
        txtduocpham.setText(tbhienthi.getValueAt(chondong, 1) + "");
        txtngayxuat.setText(tbhienthi.getValueAt(chondong, 2) + "");
        txtsoluong.setText(tbhienthi.getValueAt(chondong, 4) + "");
        txtdvitinh.setText(tbhienthi.getValueAt(chondong, 5) + "");
        txtgiaban.setText(tbhienthi.getValueAt(chondong, 6) + "");
        txtghichu.setText(tbhienthi.getValueAt(chondong, 7) + "");
    }//GEN-LAST:event_tbhienthiMouseClicked

    private void cbbNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgay1ActionPerformed
        txtngayxuat.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNgay1ActionPerformed

    private void cbbThang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThang1ActionPerformed
        txtngayxuat.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbThang1ActionPerformed

    private void cbbNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNam1ActionPerformed
        txtngayxuat.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNam1ActionPerformed

    private void btnchondpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchondpActionPerformed
        // TODO add your handling code here:
        new frmChonDuocPham().setVisible(true);
        ChonDuocPhamNhapXuat.setLeggee(2);
        this.dispose();
    }//GEN-LAST:event_btnchondpActionPerformed

    private void butNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butNhapHangMouseExited

    }//GEN-LAST:event_butNhapHangMouseExited

    private boolean checkInputOK() {
        if (txtngayxuat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập ngày xuất hàng");
            return false;
        }
        if (txtsoluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Số Lượng");
            return false;
        }
        try {
            if (Integer.parseInt(txtsoluong.getText()) < 0) {
                throw new Exception();
            }
            if (Integer.parseInt(txtgiaban.getText()) < 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng, giá nhập, giá bán phải là số >= 0");
            return false;
        }
        return true;
    }

    private void butNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNhapHangActionPerformed
        PhieuXuatContronler a = new PhieuXuatContronler();
        ResultSet reset = null;
        DuocPhamContronler dp = new DuocPhamContronler();

        if (checkInputOK()) {
            String tendp = txtduocpham.getText();
            String ngayxuat = txtngayxuat.getText();
            String dvitinh = txtdvitinh.getText();
            double giaban = Double.parseDouble(txtgiaban.getText());
            String ghichu = txtghichu.getText();
            int soluong = (Integer.parseInt(txtsoluong.getText()));
            String khachhang = cbokhachhang.getSelectedItem().toString();

            try {
                reset = dp.GetSoLuong(tendp);
                while (reset.next()) {
                    if (soluong > reset.getInt("soluong")) {
                        JOptionPane.showMessageDialog(null, "Số lượng xuất ra phải nhỏ hơn số lượng hiện có");
                    } else {
                        dp.SetSoLuong(tendp, reset.getInt("soluong") - soluong);

                        a.Insert(tendp, ngayxuat, khachhang, soluong, dvitinh, giaban, ghichu);
                        DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
                        model.setRowCount(0);
                        reset = a.GetData();
                        int i = 0;
                        int k = 1;
                        while (reset.next()) {
                            model.setRowCount(++k);
                            tbhienthi.setValueAt(reset.getString("maphieuxuat"), i, 0);
                            tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                            tbhienthi.setValueAt(reset.getString("ngayxuat"), i, 2);
                            tbhienthi.setValueAt(reset.getString("tenkhach"), i, 3);
                            tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                            tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                            tbhienthi.setValueAt(reset.getString("giaban"), i, 6);
                            tbhienthi.setValueAt(reset.getString("ghichu"), i, 7);
                            i++;
                        }
                    }
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            } catch (IOException ex) {
                Logger.getLogger(frmQLPhieuXuat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_butNhapHangActionPerformed

    private void butSuaPhieuNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butSuaPhieuNhapMouseExited

    }//GEN-LAST:event_butSuaPhieuNhapMouseExited

    private void butSuaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSuaPhieuNhapActionPerformed
        PhieuXuatContronler a = new PhieuXuatContronler();
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        String sopx = tbhienthi.getValueAt(chondong, 0) + "";
        String ngayxuat = txtngayxuat.getText();
        String ghichu = txtghichu.getText();
        int soluong = (Integer.parseInt(txtsoluong.getText()));
        String khachhang = cbokhachhang.getSelectedItem().toString();
        try {
            a.Update(sopx, ngayxuat, khachhang, soluong, ghichu);
            DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
            model.setRowCount(0);
            ResultSet reset = a.GetData();
            int i = 0;
            int k = 1;
            while (reset.next()) {
                model.setRowCount(++k);
                tbhienthi.setValueAt(reset.getString("maphieuxuat"), i, 0);
                tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbhienthi.setValueAt(reset.getString("ngayxuat"), i, 2);
                tbhienthi.setValueAt(reset.getString("tenkhach"), i, 3);
                tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                tbhienthi.setValueAt(reset.getString("giaban"), i, 6);
                tbhienthi.setValueAt(reset.getString("ghichu"), i, 7);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_butSuaPhieuNhapActionPerformed

    private void butPhieuMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPhieuMoiActionPerformed
        txtmaphieu.setText("");
        txtdvitinh.setText("");
        txtghichu.setText("");
        txtsoluong.setText("");
        txtgiaban.setText("");
        txtngayxuat.setText(java.time.LocalDate.now().toString());
    }//GEN-LAST:event_butPhieuMoiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        PhieuXuatContronler pn = new PhieuXuatContronler();
        int chondong = 0;
        chondong = tbhienthi.getSelectedRow();
        String sopx = tbhienthi.getValueAt(chondong, 0) + " ";
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (ret != JOptionPane.YES_OPTION) {
            return;
        } else {
            try {
                pn.Delete(sopx);
                DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
                model.setRowCount(0);
                ResultSet reset = pn.GetData();
                int i = 0;
                int k = 1;
                while (reset.next()) {
                    model.setRowCount(++k);
                    tbhienthi.setValueAt(reset.getString("maphieuxuat"), i, 0);
                    tbhienthi.setValueAt(reset.getString("tenduocpham"), i, 1);
                    tbhienthi.setValueAt(reset.getString("ngayxuat"), i, 2);
                    tbhienthi.setValueAt(reset.getString("tenkhach"), i, 3);
                    tbhienthi.setValueAt(reset.getString("soluong"), i, 4);
                    tbhienthi.setValueAt(reset.getString("donvitinh"), i, 5);
                    tbhienthi.setValueAt(reset.getString("giaban"), i, 6);
                    tbhienthi.setValueAt(reset.getString("ghichu"), i, 7);
                    i++;
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        try {
            // TODO add your handling code here:
            new frmMainFrame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(frmQLPhieuXuat.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void txtmaphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaphieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaphieuActionPerformed

    private void txtngayxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayxuatActionPerformed
        // TODO add your handling code here:
        txtsoluong.requestFocus();
    }//GEN-LAST:event_txtngayxuatActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
        cbokhachhang.requestFocus();
    }//GEN-LAST:event_txtsoluongActionPerformed

    private void cbokhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokhachhangActionPerformed
        // TODO add your handling code here:
        txtdvitinh.requestFocus();
    }//GEN-LAST:event_cbokhachhangActionPerformed

    private void txtdvitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdvitinhActionPerformed
        // TODO add your handling code here:
        txtghichu.requestFocus();
    }//GEN-LAST:event_txtdvitinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLPhieuXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frmQLPhieuXuat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmQLPhieuXuat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    public javax.swing.JButton btnchondp;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton butNhapHang;
    private javax.swing.JButton butPhieuMoi;
    private javax.swing.JButton butSuaPhieuNhap;
    private javax.swing.JComboBox cbbNam1;
    private javax.swing.JComboBox cbbNgay1;
    private javax.swing.JComboBox cbbThang1;
    private javax.swing.JComboBox<String> cbokhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhienthi;
    public javax.swing.JTextField txtduocpham;
    public javax.swing.JTextField txtdvitinh;
    public javax.swing.JTextField txtghichu;
    public javax.swing.JTextField txtgiaban;
    private javax.swing.JTextField txtmaphieu;
    private javax.swing.JTextField txtngayxuat;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
