
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import unit.controller.DuocPhamContronler;
import unit.controller.ToaThuocContronler;
import unit.data.JDBCConnection;
import works.DateTimeMaster;

/**
 *
 * @author admin
 */
public class frmQLToaThuoc extends javax.swing.JFrame {

    /**
     * Creates new form frmQLToaThuoc
     */
    public frmQLToaThuoc() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtngayke.setText(java.time.LocalDate.now().toString());

        cbbNgay1.setSelectedItem(DateTimeMaster.getDate());
        cbbThang1.setSelectedItem(DateTimeMaster.getMonth());
        //year
        int y = Integer.parseInt(DateTimeMaster.getYear());
        Vector v = new Vector();
        for (int i = y - 5; i <= y + 5; i++) {
            v.add(i + "");
        }
        cbbNam1.setModel(new DefaultComboBoxModel(v));
        //
        cbbNam1.setSelectedItem(DateTimeMaster.getYear());
        Statement st = null;
        ResultSet reset = null;
        try {
            java.sql.Connection conn = JDBCConnection.getJDBCConnection();
            st = conn.createStatement();
            reset = st.executeQuery("select *from khachhang");
            Vector<String> data = new Vector<String>();
            while (reset.next()) {
                data.addElement(reset.getString("makhach"));
                cbokhachhang.setModel(new DefaultComboBoxModel(data));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonDuocPham.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            DuocPhamContronler pt = new DuocPhamContronler();
            reset = pt.GetData();
            int i = 0;
            while ((reset != null) && (reset.next())) {
                tbdanhsachdp.setValueAt(reset.getString("maduocpham"), i, 0);
                tbdanhsachdp.setValueAt(reset.getString("tenduocpham"), i, 1);
                tbdanhsachdp.setValueAt(reset.getString("loaiduocpham"), i, 2);
                tbdanhsachdp.setValueAt(reset.getString("dutrutoida"), i, 3);
                tbdanhsachdp.setValueAt(reset.getString("soluong"), i, 4);
                tbdanhsachdp.setValueAt(reset.getString("donvitinh"), i, 5);
                tbdanhsachdp.setValueAt(reset.getString("gianhap"), i, 6);
                tbdanhsachdp.setValueAt(reset.getString("giaban"), i, 7);
                tbdanhsachdp.setValueAt(reset.getString("ghichu"), i, 8);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmQLToaThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmaphieu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtngayke = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtthanhtien = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        cbbNgay1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbbThang1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbbNam1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cbokhachhang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtghichu = new javax.swing.JTextField();
        btntinhtien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnloaibo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbduocpham = new javax.swing.JTable();
        btntoathuocmoi = new javax.swing.JButton();
        btnxuattoathuoc = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        panelChonDP = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnchonduocpham = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblmadp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnthemvaotoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbltendp = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelCenter1 = new javax.swing.JPanel();
        panelChonDP1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblchndp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdanhsachdp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("PHIẾU KÊ ĐƠN THUỐC");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin toa thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(102, 0, 0))); // NOI18N

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã phiếu*");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 14));

        txtmaphieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmaphieu.setEnabled(false);
        txtmaphieu.setPreferredSize(new java.awt.Dimension(120, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Khách hàng*");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 14));

        txtngayke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtngayke.setPreferredSize(new java.awt.Dimension(120, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ngày kê*");
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tổng tiền thuốc*");
        jLabel9.setPreferredSize(new java.awt.Dimension(80, 14));

        txtthanhtien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtthanhtien.setEnabled(false);
        txtthanhtien.setPreferredSize(new java.awt.Dimension(120, 27));
        txtthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthanhtienActionPerformed(evt);
            }
        });

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        cbbNgay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbbNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgay1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNgay1);

        jLabel11.setText("/");
        jPanel16.add(jLabel11);

        cbbThang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbThang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThang1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbThang1);

        jLabel12.setText("/");
        jPanel16.add(jLabel12);

        cbbNam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013" }));
        cbbNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNam1ActionPerformed(evt);
            }
        });
        jPanel16.add(cbbNam1);

        jLabel14.setText(" ");
        jPanel16.add(jLabel14);

        cbokhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbokhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ghi chú");

        txtghichu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btntinhtien.setBackground(new java.awt.Color(255, 221, 255));
        btntinhtien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntinhtien.setForeground(new java.awt.Color(0, 0, 255));
        btntinhtien.setText("Tính tiền thuốc");
        btntinhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhtienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtngayke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbokhachhang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtmaphieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtthanhtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btntinhtien))
                        .addComponent(txtghichu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbokhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtngayke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntinhtien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các dược phẩm đã chọn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnloaibo.setBackground(new java.awt.Color(153, 153, 255));
        btnloaibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnloaibo.setForeground(new java.awt.Color(153, 0, 51));
        btnloaibo.setText("Loại bỏ dược phẩm");
        btnloaibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloaiboActionPerformed(evt);
            }
        });

        tbduocpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbduocpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dược phẩm", "Tên dược phẩm", "Số lượng", "Giá bán", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbduocpham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnloaibo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnloaibo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btntoathuocmoi.setBackground(new java.awt.Color(204, 0, 51));
        btntoathuocmoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntoathuocmoi.setForeground(new java.awt.Color(255, 255, 255));
        btntoathuocmoi.setText("Toa thuốc mới");
        btntoathuocmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntoathuocmoiActionPerformed(evt);
            }
        });

        btnxuattoathuoc.setBackground(new java.awt.Color(204, 0, 51));
        btnxuattoathuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxuattoathuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnxuattoathuoc.setText("Xuất toa thuốc");
        btnxuattoathuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuattoathuocActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(204, 0, 51));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 242, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn dược phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        panelCenter.setLayout(new java.awt.GridLayout(1, 0));

        panelChonDP.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());
        panelChonDP.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnchonduocpham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm vào toa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnchonduocpham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnchonduocpham.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Dược phẩm: ");

        lblmadp.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblmadp.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Click để nhập số lượng: ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("3");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("4");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("6");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("0");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("2");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("5");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("7");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("8");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setText("9");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        btnthemvaotoa.setBackground(new java.awt.Color(0, 204, 0));
        btnthemvaotoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthemvaotoa.setForeground(new java.awt.Color(102, 0, 0));
        btnthemvaotoa.setText("Thêm vào toa");
        btnthemvaotoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthemvaotoaMouseClicked(evt);
            }
        });
        btnthemvaotoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemvaotoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Số lượng");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("~");

        lbltendp.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbltendp.setText("jLabel13");

        javax.swing.GroupLayout pnchonduocphamLayout = new javax.swing.GroupLayout(pnchonduocpham);
        pnchonduocpham.setLayout(pnchonduocphamLayout);
        pnchonduocphamLayout.setHorizontalGroup(
            pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createSequentialGroup()
                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 221, Short.MAX_VALUE))
                            .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(lblmadp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createSequentialGroup()
                                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createSequentialGroup()
                                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnchonduocphamLayout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbltendp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(87, 87, 87)))))
                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(pnchonduocphamLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnthemvaotoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnchonduocphamLayout.setVerticalGroup(
            pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnchonduocphamLayout.createSequentialGroup()
                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblmadp)
                    .addComponent(jLabel10)
                    .addComponent(lbltendp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnchonduocphamLayout.createSequentialGroup()
                        .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6)
                                .addComponent(jButton1))
                            .addComponent(jButton7)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8)
                                .addComponent(jButton9))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnchonduocphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton10)
                                .addComponent(jButton5)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnthemvaotoa)
                .addGap(51, 51, 51))
        );

        panelChonDP.add(pnchonduocpham, java.awt.BorderLayout.CENTER);

        panelCenter.add(panelChonDP);

        jPanel3.add(panelCenter, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 242, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn dược phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        panelCenter1.setLayout(new java.awt.GridLayout(1, 0));

        panelChonDP1.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        lblchndp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblchndp.setText("Tìm dược phẩm ở đây: ");
        jPanel6.add(lblchndp, java.awt.BorderLayout.LINE_START);

        panelChonDP1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        tbdanhsachdp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbdanhsachdp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã dược phẩm", "Tên dược phẩm", "Loại dược phẩm", "Số lượng dự trữ", "Số lượng hiện có", "Đơn vị tính", "Giá nhập", "Giá bán", "Ghi chú"
            }
        ));
        tbdanhsachdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdanhsachdpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdanhsachdp);

        panelChonDP1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelCenter1.add(panelChonDP1);

        jPanel5.add(panelCenter1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btntoathuocmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnxuattoathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(16, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnxuattoathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntoathuocmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new frmMainFrame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(frmQLToaThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private boolean checkFieldsOK() {
        txtngayke.setText(txtngayke.getText().trim());
        if (txtngayke.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập ngày kê đơn");
            return false;
        }
        if (txtthanhtien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa hiển thị tổng tiền thuốc");
            return false;
        }
        try {
            if (Double.parseDouble(txtthanhtien.getText()) <= 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tổng tiền phải là số > 0");
            return false;
        }
        return true;
    }
    private void btnloaiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloaiboActionPerformed
        // TODO add your handling code here:
        int row = tbduocpham.getSelectedRow();
        DefaultTableModel modeltb = (DefaultTableModel) tbduocpham.getModel();

        ResultSet reset = null;
        DuocPhamContronler dp = new DuocPhamContronler();
        String madp = modeltb.getValueAt(row, 0).toString();
        String soluong = modeltb.getValueAt(row, 2).toString();

        try {
            reset = dp.GetMa(madp);
            while (reset.next()) {
                reset = dp.GetSoLuong(madp);
                while (reset.next()) {
                    dp.SetSoLuong(madp, reset.getInt("soluong") + Integer.parseInt(soluong));

                    modeltb.removeRow(row);
                    txtthanhtien.setText("");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (IOException ex) {
            Logger.getLogger(frmQLToaThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnloaiboActionPerformed

    private void btntoathuocmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntoathuocmoiActionPerformed
        // TODO add your handling code here:
        txtmaphieu.setText("");
        txtngayke.setText(java.time.LocalDate.now().toString());
        txtsoluong.setText("");
        txtthanhtien.setText("");
    }//GEN-LAST:event_btntoathuocmoiActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton1.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton6.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton2.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton3.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton7.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton4.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton8.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton9.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton10.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String chuoi = this.jButton5.getText();
        this.txtsoluong.setText(chuoi);
    }//GEN-LAST:event_jButton5MouseClicked

    private void cbbNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNam1ActionPerformed
        txtngayke.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNam1ActionPerformed

    private void cbbThang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThang1ActionPerformed
        txtngayke.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbThang1ActionPerformed

    private void cbbNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgay1ActionPerformed
        txtngayke.setText(cbbNam1.getSelectedItem() + "-" + cbbThang1.getSelectedItem() + "-" + cbbNgay1.getSelectedItem());
    }//GEN-LAST:event_cbbNgay1ActionPerformed

    private void btnthemvaotoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemvaotoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemvaotoaMouseClicked

    private void btnthemvaotoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemvaotoaActionPerformed
        // TODO add your handling code here:).log(Level.SEVERE, null, ex);
        ResultSet reset = null;
        DuocPhamContronler dp = new DuocPhamContronler();

        int soluong = Integer.parseInt(txtsoluong.getText());
        int index = tbdanhsachdp.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();
        String madp = model.getValueAt(index, 0).toString();
        String tendp = model.getValueAt(index, 1).toString();
        double giaban = Double.parseDouble(model.getValueAt(index, 7).toString());
        double thanhtien = soluong * giaban;

        DefaultTableModel modeltb = (DefaultTableModel) tbduocpham.getModel();
        try {
            reset = dp.GetSoLuong(madp);
            while (reset.next()) {
                if (soluong > reset.getInt("soluong")) {
                    JOptionPane.showMessageDialog(null, "Số lượng lấy ra phải nhỏ hơn số lượng hiện có");
                } else if (reset.getInt("soluong") == 0) {
                    JOptionPane.showMessageDialog(null, "Số lượng hiện có = 0");
                } else {
                    dp.SetSoLuong(madp, reset.getInt("soluong") - soluong);

                    modeltb.insertRow(0, new Object[]{madp, tendp, soluong, giaban, thanhtien});
                    txtthanhtien.setText("");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (IOException ex) {
            Logger.getLogger(frmQLToaThuoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthemvaotoaActionPerformed

    private void btnxuattoathuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuattoathuocActionPerformed
        // TODO add your handling code here:
        ToaThuocContronler tt = new ToaThuocContronler();
        if (checkFieldsOK()) {
            String ngayke = txtngayke.getText();
            String khachhang = cbokhachhang.getSelectedItem().toString();
            double tongtien = Double.parseDouble(txtthanhtien.getText());
            String ghichu = txtghichu.getText();

            try {
                tt.Insert(ngayke, khachhang, tongtien, ghichu);
            } catch (SQLException ex) {
                Logger.getLogger(frmQLToaThuoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnxuattoathuocActionPerformed

    private void btntinhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhtienActionPerformed
        // TODO add your handling code here:
        int n = tbduocpham.getRowCount();
        double[] arr = new double[n];
        String tien;
        double tongtienthuoc = 0;

        for (int i = 0; i < tbduocpham.getColumnCount(); i++) {
            for (int j = 0; j < tbduocpham.getRowCount(); j++) {
                if (i == 4) {
                    Object tienthuoc = tbduocpham.getValueAt(j, i);
                    if (tbduocpham.getValueAt(j, i) != null) {
                        tien = tienthuoc.toString();
                        arr[i] = Double.parseDouble(tien);
                        tongtienthuoc += arr[i];
                    }
                }
            }
        }
        txtthanhtien.setText(Double.toString(tongtienthuoc));
    }//GEN-LAST:event_btntinhtienActionPerformed

    private void txtthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthanhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtthanhtienActionPerformed

    private void tbdanhsachdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdanhsachdpMouseClicked
        // TODO add your handling code here:

        int index = tbdanhsachdp.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbdanhsachdp.getModel();

        String madp = model.getValueAt(index, 0).toString();
        String tendp = model.getValueAt(index, 1).toString();

        lblmadp.setText(madp);
        lbltendp.setText(tendp);

    }//GEN-LAST:event_tbdanhsachdpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLToaThuoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLToaThuoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLToaThuoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLToaThuoc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmQLToaThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnloaibo;
    private javax.swing.JButton btnthemvaotoa;
    private javax.swing.JButton btntinhtien;
    private javax.swing.JButton btntoathuocmoi;
    private javax.swing.JButton btnxuattoathuoc;
    private javax.swing.JComboBox cbbNam1;
    private javax.swing.JComboBox cbbNgay1;
    private javax.swing.JComboBox cbbThang1;
    private javax.swing.JComboBox<String> cbokhachhang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblchndp;
    public javax.swing.JLabel lblmadp;
    private javax.swing.JLabel lbltendp;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCenter1;
    private javax.swing.JPanel panelChonDP;
    private javax.swing.JPanel panelChonDP1;
    private javax.swing.JPanel pnchonduocpham;
    private javax.swing.JTable tbdanhsachdp;
    private javax.swing.JTable tbduocpham;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtmaphieu;
    private javax.swing.JTextField txtngayke;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txtthanhtien;
    // End of variables declaration//GEN-END:variables
}
